version: '2'
services:
    server:
        container_name: hello-world
        depends_on:
            - db
        build:
            context: helloworld_api
            dockerfile: Dockerfile
        image: helloworld_api:latest
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/DB-USERNAME   ### replace the DB-USERNAME with your desired USERNAME      
            - SPRING_DATASOURCE_USERNAME=DB-USERNAME                        ### replace the DB-USERNAME with your desired USERNAME
            - SPRING_DATASOURCE_PASSWORD=DB-PASSWORD                        ### replace the DB-PASSWORD with your desired PASSWORD
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        ports:
            - 80:8080
        networks:
            - spring-cloud-network
    db:
        image: 'postgres:13.1-alpine'
        container_name: db
        environment:
            - POSTGRES_USER=DB-USERNAME                                     ### replace the DB-USERNAME with your desired USERNAME
            - POSTGRES_PASSWORD=DB-PASSWORD                                 ### replace the DB-PASSWORD with your desired PASSWORD
        ports:
            - 5432:5432
        networks:
            - spring-cloud-network

    pgadmin:
        container_name: pgadmin4_container
        depends_on:
            - server
        image: dpage/pgadmin4

        environment:
            - PGADMIN_DEFAULT_EMAIL=PGADMIN-EMA                             ### replace the PGADMIN-EMAIL with your desired EMAIL
            - PGADMIN_DEFAULT_PASSWORD=PGADMIN-PASSWORD                     ### replace the PGADMIN-PASSWORD with your desired PASSWORD
        ports:
            - "5050:80"
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge